### ISSUE TITLE
[Feat] Works v1

### ISSUE THREAD

**Issue by vaegtersang** [grao3/.github#2]
This user story tracks the work needed to post and read a work on GrAO3. 

### Core Use-Case
I want to be able to create and read a fic on GrAO3.

### Sub-stories
**Schema**
- [ ] Define a bare-bones work schema [(Issue)](https://github.com/grao3/schemata/issues/2).

**Author CRUD** 
- [ ] Allow a user to post works
- [ ] Allow a user to delete works.
- [ ] Allow a user to edit a work info.
- [ ] Allow a user to add chapters
- [ ] Allow a user to delete chapters
- [ ] Allow a user to edit chapters

**Reader User Stories**
- [ ] Allow a reader to view an entire series.
- [ ] Allow a reader to view an entire work.
- [ ] Allow a reader to view a work by chapter. 

### Not in Scope: 
- Tags
- Comments
- "Related works", e.g., translations, remixes, ...
- Favorites, bookmarks, kudos, ...
